# Generated by Django 4.1.7 on 2023-02-20 20:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0002_post_delete_blog_delete_planta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posteo',
        ),
    ]
