# Generated by Django 4.1.7 on 2023-02-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_post_posteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('posteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppCoder.posteo')),
            ],
        ),
    ]
