# Generated by Django 4.1.7 on 2023-02-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteo',
            old_name='descripcion',
            new_name='cuerpo',
        ),
    ]
