# Generated by Django 4.1.7 on 2023-02-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_descripcion_posteo_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='posteo',
            name='subtitulo',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
