# Generated by Django 4.1.7 on 2023-03-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='perfil_pic',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/perfil/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='web_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
